#!/bin/bash

# add hhvm repo
wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
echo deb http://dl.hhvm.com/ubuntu trusty main | sudo tee /etc/apt/sources.list.d/hhvm.list

# before installing
sudo apt-get update
sudo apt-get upgrade -y

# prepare password for mysql installation
sudo debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password password mysqlhehehe'
sudo debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password_again password mysqlhehehe'

# installing packages
sudo apt-get install -y unzip hhvm nginx mysql-server-5.5 mysql-client vim zsh

# setup hhvm
sudo /usr/share/hhvm/install_fastcgi.sh
sudo /etc/init.d/hhvm restart
sudo /etc/init.d/nginx restart
sudo update-rc.d hhvm defaults

# download init script
curl -O https://raw.githubusercontent.com/aestik/wpvm/master/dbcaretaker
sudo mv dbcaretaker /etc/init.d/dbcaretaker

# activate init script
touch /var/log/dbcaretaker.log
cd /etc/init.d
sudo chmod +x dbcaretaker
sudo insserv dbcaretaker

# create WordPress database
mysql -u root -pmysqlhehehe <<< "CREATE DATABASE IF NOT EXISTS wordpress;"

# download Search-Replace-DB
sudo wget -c https://github.com/interconnectit/Search-Replace-DB/archive/master.zip -O /opt/search-replace.zip
sudo unzip -o /opt/search-replace.zip -d /opt/

# start dbcaretaker
sudo service dbcaretaker start
